Задание 1
FreeCourseJava/Olelife13_HomeWork pull request #2
Opened 2022-06-19 10:51 UTC by Olelife13

2022-06-19 15:06 UTC, ivtcro commented on src/Case2.java
> +        int summMin = -2147483648;
переменные нигде не используются

2022-06-19 15:06 UTC, ivtcro commented on src/Case2.java
> +        if (result < intFlow) {
если balance=-100, то результат тоже будет отрицательным и это корректно

2022-06-19 16:30 UTC, Olelife13 commented on src/Case2.java
> +        int summMin = -2147483648;
да, это я уже тут кумекаю про дополнение этого кода, но здесь могу затереть, спасиб

2022-06-19 16:31 UTC, Olelife13 commented on src/Case2.java
> +        if (result < intFlow) {
Спасибо, тут у меня кажем так, ровно задание про возврат нуля, если получается отрицательное число, 3-е дополнение я ещё не додумала пока.

2022-06-20 15:02 UTC, hyragano requested changes

2022-06-20 15:02 UTC, hyragano commented on src/Case1.java
> +        long TimeDataMillisec = DataMillise(nymberOfDaysMs);
Название переменной с маленькойБуквы

2022-06-20 15:02 UTC, hyragano commented on src/Case1.java
> +    public static long DataMillise(long nymberOfDaysMs){
метод должен принимать колличество дней, и уже тут умножать там на миллисекунды и прочее, иначе у тебя получается метод только складывает.

2022-06-20 17:26 UTC, hyragano requested changes

2022-06-20 17:26 UTC, hyragano commented on src/Case2.java
> +        if (result < intFlow) {
Ок

2022-06-20 17:26 UTC, hyragano commented on src/Case3.java
> +                if (summ>Integer.MAX_VALUE|summ<Integer.MIN_VALUE){
мы пока | а точнее || не проходили. Попробуй подмать как можно через кастинг решить проблему?

2022-06-20 17:54 UTC, hyragano requested changes

2022-06-20 17:54 UTC, hyragano commented on src/Case1.java
> +            long DayToday = System.currentTimeMillis();
да. название переменных с маленькойБуквыCamelCase

2022-06-20 17:54 UTC, hyragano commented on src/Case2.java
> +        int TotalBalance = increaseBalance(balance,bonus);
camelCase

2022-06-20 18:01 UTC, Olelife13 commented on src/Case3.java
> +                if (summ>Integer.MAX_VALUE|summ<Integer.MIN_VALUE){
Ну, это мне захотелось впихнуть 2 условия проверки разом и на просторах интернета  я нашла как, неправильно?

2022-06-20 18:14 UTC, Olelife13 commented on src/Case2.java
> +        int TotalBalance = increaseBalance(balance,bonus);
ок, поправила

2022-06-20 18:20 UTC, Olelife13 commented on src/Case1.java
> +            long DayToday = System.currentTimeMillis();
ок, поправила

2022-06-22 03:52 UTC, merged